### ISSUE TITLE
Can't launch the simulation with CoppeliaSim 4.6

### ISSUE THREAD

**Issue by Luczia** [giulioturrisi/Self-Balancing-Robot#3]
Hi, I'm trying to use the simulation, through docker, following the readme but I get the error :

```
./coppeliaSim.sh -s self_balancing_robot.ttt 
the argument ('/home/coppeliasim_simulation/self_balancing_robot.ttt') for option '--auto-start' is invalid
```

when running the command : 
`./coppeliaSim.sh -s self_balancing_robot.ttt `

I don't understand what the coppeliaSim.sh script does, but I belive my path file is ok.

Any hint ?

**Comment by giulioturrisi** [comment]
Hi Luczia, I will have a look at the problem later this week. I will let you know.

**Comment by Luczia** [comment]
Awesome, 

In the meantime, I could workaround by opening manually the self_balancing_robot.ttt from the CoppeliaSim GUI.

There was also an issue with obsolete naming of "np.float" (renamed as "float"  in latest verison of numpy or panda).
(about 6 occurrences to changes in the source code). Not hard to implement, but you may want to update it.

**Comment by giulioturrisi** [comment]
added the new command to start coppeliaSim from terminal (-f instead of -s in the previous one) and updated the README. Now there is a new way to install everything with conda.
